"""
Comprehensive Clinical Knowledge Base for ICD-10 and RxNorm standard codes.
"""

def get_comprehensive_concepts() -> list[dict[str, str]]:
    concepts = [
        # Common Disease Concepts (CHẨN_ĐOÁN / DISEASE)
        {"code": "D55.0", "display": "thiếu men G6PD", "type": "DISEASE"},
        {"code": "D55.0", "display": "bệnh thiếu men G6PD", "type": "DISEASE"},
        {"code": "D55.0", "display": "G6PD deficiency", "type": "DISEASE"},
        {"code": "J84.9", "display": "bệnh phổi kẽ", "type": "DISEASE"},
        {"code": "J84.9", "display": "phổi kẽ", "type": "DISEASE"},
        {"code": "D84.9", "display": "suy giảm miễn dịch", "type": "DISEASE"},
        {"code": "L03.9", "display": "viêm mô tế bào", "type": "DISEASE"},
        {"code": "N90.8", "display": "tổn thương vùng âm hộ", "type": "DISEASE"},
        {"code": "N90.8", "display": "tổn thương vùng âm hộ phải", "type": "DISEASE"},
        {"code": "G20", "display": "bệnh Parkinson", "type": "DISEASE"},
        {"code": "G20", "display": "Parkinson", "type": "DISEASE"},
        {"code": "M30.3", "display": "bệnh Kawasaki", "type": "DISEASE"},
        {"code": "M30.3", "display": "Kawasaki", "type": "DISEASE"},
        {"code": "E28.2", "display": "hội chứng buồng trứng đa nang", "type": "DISEASE"},
        {"code": "E28.2", "display": "buồng trứng đa nang", "type": "DISEASE"},
        {"code": "C22.1", "display": "ung thư biểu mô tế bào mật", "type": "DISEASE"},
        {"code": "C22.1", "display": "cholangiocarcinoma", "type": "DISEASE"},
        {"code": "C92.1", "display": "bạch cầu dòng tủy mạn tính", "type": "DISEASE"},
        {"code": "C92.1", "display": "CML", "type": "DISEASE"},
        {"code": "I20.9", "display": "đau thắt ngực", "type": "DISEASE"},
        {"code": "I25.9", "display": "thiếu máu cơ tim", "type": "DISEASE"},
        {"code": "I21.9", "display": "nhồi máu cơ tim", "type": "DISEASE"},
        {"code": "I63.9", "display": "đột quỵ", "type": "DISEASE"},
        {"code": "I63.9", "display": "tai biến mạch máu não", "type": "DISEASE"},
        {"code": "I10", "display": "Tăng huyết áp", "type": "DISEASE"},
        {"code": "I10", "display": "tăng huyết áp nguyên phát", "type": "DISEASE"},
        {"code": "I10", "display": "cao huyết áp", "type": "DISEASE"},
        {"code": "E11.9", "display": "đái tháo đường", "type": "DISEASE"},
        {"code": "E11.9", "display": "tiểu đường", "type": "DISEASE"},
        {"code": "K21.9", "display": "trào ngược dạ dày thực quản", "type": "DISEASE"},
        {"code": "K21.9", "display": "trào ngược dạ dày", "type": "DISEASE"},
        {"code": "K21.9", "display": "GERD", "type": "DISEASE"},
        {"code": "J18.9", "display": "viêm phổi", "type": "DISEASE"},
        {"code": "J18.9", "display": "viêm phổi cộng đồng", "type": "DISEASE"},
        {"code": "A15.0", "display": "lao phổi", "type": "DISEASE"},
        {"code": "K70.3", "display": "xơ gan do rượu", "type": "DISEASE"},
        {"code": "K74.6", "display": "xơ gan", "type": "DISEASE"},
        {"code": "I50.9", "display": "suy tim", "type": "DISEASE"},
        {"code": "B18.2", "display": "viêm gan C", "type": "DISEASE"},
        {"code": "B18.1", "display": "viêm gan B", "type": "DISEASE"},
        {"code": "M10.9", "display": "bệnh gút", "type": "DISEASE"},
        {"code": "M10.9", "display": "gút", "type": "DISEASE"},
        {"code": "J45.9", "display": "hen phế quản", "type": "DISEASE"},
        {"code": "J45.9", "display": "hen suyễn", "type": "DISEASE"},
        {"code": "J20.9", "display": "viêm phế quản", "type": "DISEASE"},
        {"code": "D59.9", "display": "thiếu máu tan huyết", "type": "DISEASE"},
        {"code": "D59.9", "display": "tan huyết", "type": "DISEASE"},
        {"code": "D64.9", "display": "thiếu máu", "type": "DISEASE"},
        {"code": "N17.9", "display": "suy thận cấp", "type": "DISEASE"},
        {"code": "N18.9", "display": "suy thận mạn", "type": "DISEASE"},
        {"code": "N18.9", "display": "suy thận", "type": "DISEASE"},
        {"code": "N39.0", "display": "nhiễm khuẩn đường tiết niệu", "type": "DISEASE"},
        {"code": "E78.5", "display": "tăng lipid máu", "type": "DISEASE"},
        {"code": "M48.0", "display": "hẹp ống sống", "type": "DISEASE"},
        {"code": "L50.9", "display": "mày đay", "type": "DISEASE"},
        {"code": "L50.9", "display": "nổi mề đay", "type": "DISEASE"},
        {"code": "O14.9", "display": "tiền sản giật", "type": "DISEASE"},
        {"code": "N04.9", "display": "hội chứng thận hư", "type": "DISEASE"},
        {"code": "K76.0", "display": "gan nhiễm mỡ", "type": "DISEASE"},
        {"code": "K80.2", "display": "sỏi mật", "type": "DISEASE"},
        {"code": "N20.0", "display": "sỏi thận", "type": "DISEASE"},
        {"code": "K35.8", "display": "viêm ruột thừa", "type": "DISEASE"},
        {"code": "A82", "display": "bệnh dại", "type": "DISEASE"},
        {"code": "B01.9", "display": "thủy đậu", "type": "DISEASE"},
        {"code": "B05", "display": "bệnh sởi", "type": "DISEASE"},
        {"code": "A90", "display": "sốt xuất huyết", "type": "DISEASE"},
        {"code": "F32.9", "display": "trầm cảm", "type": "DISEASE"},
        {"code": "E85.9", "display": "thoái hóa tinh bột", "type": "DISEASE"},
        {"code": "E85.9", "display": "amyloidosis", "type": "DISEASE"},

        # Common Symptom Concepts (TRIỆU_CHỨNG / SYMPTOM)
        {"code": "R50.9", "display": "Sốt cao", "type": "SYMPTOM"},
        {"code": "R50.9", "display": "sốt", "type": "SYMPTOM"},
        {"code": "R00.0", "display": "Tim đập nhanh", "type": "SYMPTOM"},
        {"code": "R00.0", "display": "hồi hộp đánh trống ngực", "type": "SYMPTOM"},
        {"code": "R06.0", "display": "khó thở", "type": "SYMPTOM"},
        {"code": "R06.02", "display": "khó thở khi gắng sức", "type": "SYMPTOM"},
        {"code": "R17", "display": "Vàng da", "type": "SYMPTOM"},
        {"code": "R17", "display": "vàng mắt", "type": "SYMPTOM"},
        {"code": "R10.9", "display": "đau bụng", "type": "SYMPTOM"},
        {"code": "R10.9", "display": "Đau bụng", "type": "SYMPTOM"},
        {"code": "R11.0", "display": "Buồn nôn", "type": "SYMPTOM"},
        {"code": "R11", "display": "nôn", "type": "SYMPTOM"},
        {"code": "R52", "display": "đau", "type": "SYMPTOM"},
        {"code": "R05", "display": "ho", "type": "SYMPTOM"},
        {"code": "R05", "display": "ho khan", "type": "SYMPTOM"},
        {"code": "R05", "display": "ho đờm", "type": "SYMPTOM"},
        {"code": "R53.83", "display": "mệt mỏi", "type": "SYMPTOM"},
        {"code": "R60.9", "display": "phù", "type": "SYMPTOM"},
        {"code": "R60.9", "display": "phù nề", "type": "SYMPTOM"},
        {"code": "R51", "display": "đau đầu", "type": "SYMPTOM"},
        {"code": "R07.4", "display": "tức ngực", "type": "SYMPTOM"},
        {"code": "R07.4", "display": "đau ngực", "type": "SYMPTOM"},
        {"code": "R42", "display": "chóng mặt", "type": "SYMPTOM"},
        {"code": "R19.7", "display": "tiêu chảy", "type": "SYMPTOM"},
        {"code": "K59.0", "display": "táo bón", "type": "SYMPTOM"},
        {"code": "R25.1", "display": "run tay", "type": "SYMPTOM"},
        {"code": "R20.2", "display": "tê bì", "type": "SYMPTOM"},
        {"code": "H93.1", "display": "ù tai", "type": "SYMPTOM"},
        {"code": "H53.9", "display": "rối loạn thị lực", "type": "SYMPTOM"},
        {"code": "R26.81", "display": "mất thăng bằng", "type": "SYMPTOM"},
        {"code": "R63.0", "display": "chán ăn", "type": "SYMPTOM"},
        {"code": "R63.4", "display": "sụt cân", "type": "SYMPTOM"},
        {"code": "E66.9", "display": "béo phì", "type": "SYMPTOM"},

        # Common Drug Concepts (THUỐC / MEDICINE)
        {"code": "308135", "display": "amlodipine 10 mg", "type": "MEDICINE"},
        {"code": "308135", "display": "amlodipine 10mg", "type": "MEDICINE"},
        {"code": "243670", "display": "aspirin 81 mg", "type": "MEDICINE"},
        {"code": "243670", "display": "aspirin 81mg", "type": "MEDICINE"},
        {"code": "866436", "display": "metoprolol succinate xl 50 mg", "type": "MEDICINE"},
        {"code": "866436", "display": "metoprolol 50 mg", "type": "MEDICINE"},
        {"code": "392085", "display": "guaifenesin", "type": "MEDICINE"},
        {"code": "7597", "display": "nystatin", "type": "MEDICINE"},
        {"code": "313782", "display": "acetaminophen 325-650 mg", "type": "MEDICINE"},
        {"code": "313782", "display": "paracetamol 500 mg", "type": "MEDICINE"},
        {"code": "904475", "display": "pravastatin 40 mg", "type": "MEDICINE"},
        {"code": "1099279", "display": "docusate sodium 100 mg", "type": "MEDICINE"},
        {"code": "312935", "display": "senna 8.6 mg", "type": "MEDICINE"},
        {"code": "197527", "display": "clonazepam 0.5 mg", "type": "MEDICINE"},
        {"code": "197528", "display": "clonazepam 1.5 mg", "type": "MEDICINE"},
        {"code": "282388", "display": "gleevec", "type": "MEDICINE"},
        {"code": "282388", "display": "imatinib", "type": "MEDICINE"},
        {"code": "202433", "display": "tylenol", "type": "MEDICINE"},
        {"code": "7646", "display": "omeprazole", "type": "MEDICINE"},
        {"code": "656", "display": "allopurinol", "type": "MEDICINE"},
        {"code": "353062", "display": "suboxone", "type": "MEDICINE"},
        {"code": "11246", "display": "Vitamin K", "type": "MEDICINE"},
        {"code": "3640", "display": "doxycycline", "type": "MEDICINE"},
        {"code": "135834", "display": "bactrim", "type": "MEDICINE"},
        {"code": "7245", "display": "băng phiến", "type": "MEDICINE"},
        {"code": "1976", "display": "long não", "type": "MEDICINE"},
        {"code": "313360", "display": "đậu tằm", "type": "MEDICINE"},
        {"code": "261551", "display": "corticoid", "type": "MEDICINE"},
        {"code": "261551", "display": "corticoid liều cao", "type": "MEDICINE"},

        # Common Test Concepts (TÊN_XÉT_NGHIỆM / TEST)
        {"code": "BL", "display": "xét nghiệm máu", "type": "TEST"},
        {"code": "BL", "display": "công thức máu", "type": "TEST"},
        {"code": "UR", "display": "xét nghiệm nước tiểu", "type": "TEST"},
        {"code": "CT", "display": "chụp CT", "type": "TEST"},
        {"code": "MR", "display": "chụp MRI", "type": "TEST"},
        {"code": "XR", "display": "x-quang", "type": "TEST"},
        {"code": "US", "display": "siêu âm", "type": "TEST"},
        {"code": "US", "display": "siêu âm bụng", "type": "TEST"},
        {"code": "ECHO", "display": "siêu âm tim", "type": "TEST"},
        {"code": "ECG", "display": "điện tâm đồ", "type": "TEST"},
        {"code": "END", "display": "nội soi", "type": "TEST"},
        {"code": "BIO", "display": "sinh thiết", "type": "TEST"},
        {"code": "LFT", "display": "chức năng gan", "type": "TEST"}
    ]
    return concepts
