import json

def get_comprehensive_concepts():
    concepts = [
        # DISEASES (CHẨN_ĐOÁN) - ICD-10
        {"code": "G20", "display": "Parkinson", "type": "DISEASE"},
        {"code": "G20", "display": "bệnh Parkinson", "type": "DISEASE"},
        {"code": "G20", "display": "hội chứng Parkinson", "type": "DISEASE"},
        {"code": "E28.2", "display": "Hội chứng buồng trứng đa nang", "type": "DISEASE"},
        {"code": "E28.2", "display": "buồng trứng đa nang", "type": "DISEASE"},
        {"code": "E66.9", "display": "béo phì", "type": "DISEASE"},
        {"code": "I20.9", "display": "đau thắt ngực", "type": "DISEASE"},
        {"code": "I20.9", "display": "cơn đau thắt ngực", "type": "DISEASE"},
        {"code": "C22.1", "display": "ung thư biểu mô tế bào mật", "type": "DISEASE"},
        {"code": "C22.1", "display": "ung thư đường mật", "type": "DISEASE"},
        {"code": "I25.9", "display": "thiếu máu cơ tim", "type": "DISEASE"},
        {"code": "I25.9", "display": "bệnh cơ tim thiếu máu cục bộ", "type": "DISEASE"},
        {"code": "K30", "display": "đau bao tử", "type": "DISEASE"},
        {"code": "K30", "display": "đau dạ dày", "type": "DISEASE"},
        {"code": "K29.7", "display": "viêm dạ dày", "type": "DISEASE"},
        {"code": "L68.0", "display": "rậm lông", "type": "DISEASE"},
        {"code": "K75.9", "display": "viêm gan vàng da ứ mật", "type": "DISEASE"},
        {"code": "K75.9", "display": "ứ mật", "type": "DISEASE"},
        {"code": "D55.0", "display": "Thiếu men G6PD", "type": "DISEASE"},
        {"code": "D55.0", "display": "thiếu men G6PD", "type": "DISEASE"},
        {"code": "M30.3", "display": "Bệnh Kawasaki", "type": "DISEASE"},
        {"code": "M30.3", "display": "Kawasaki", "type": "DISEASE"},
        {"code": "I10", "display": "Tăng huyết áp", "type": "DISEASE"},
        {"code": "I10", "display": "cao huyết áp", "type": "DISEASE"},
        {"code": "E11.9", "display": "tiểu đường", "type": "DISEASE"},
        {"code": "E11.9", "display": "đái tháo đường", "type": "DISEASE"},
        {"code": "E11.9", "display": "đái tháo đường tuýp 2", "type": "DISEASE"},
        {"code": "N18.9", "display": "suy thận", "type": "DISEASE"},
        {"code": "N18.9", "display": "thận mạn", "type": "DISEASE"},
        {"code": "N18.9", "display": "suy thận mạn", "type": "DISEASE"},
        {"code": "N17.9", "display": "suy thận cấp", "type": "DISEASE"},
        {"code": "I63.9", "display": "đột quỵ", "type": "DISEASE"},
        {"code": "I63.9", "display": "tai biến mạch máu não", "type": "DISEASE"},
        {"code": "K74.6", "display": "xơ gan", "type": "DISEASE"},
        {"code": "K70.3", "display": "xơ gan do rượu", "type": "DISEASE"},
        {"code": "I50.9", "display": "suy tim", "type": "DISEASE"},
        {"code": "B18.1", "display": "viêm gan B", "type": "DISEASE"},
        {"code": "B18.2", "display": "viêm gan C", "type": "DISEASE"},
        {"code": "M10.9", "display": "gút", "type": "DISEASE"},
        {"code": "M10.9", "display": "bệnh gút", "type": "DISEASE"},
        {"code": "M11.2", "display": "Giả gout", "type": "DISEASE"},
        {"code": "J45", "display": "hen suyễn", "type": "DISEASE"},
        {"code": "J45", "display": "hen phế quản", "type": "DISEASE"},
        {"code": "J40", "display": "viêm phế quản", "type": "DISEASE"},
        {"code": "J18.9", "display": "viêm phổi", "type": "DISEASE"},
        {"code": "J18.9", "display": "viêm phổi hoại tử", "type": "DISEASE"},
        {"code": "A15.0", "display": "lao phổi", "type": "DISEASE"},
        {"code": "K21.9", "display": "trào ngược dạ dày", "type": "DISEASE"},
        {"code": "K21.9", "display": "trào ngược dạ dày thực quản", "type": "DISEASE"},
        {"code": "K21.9", "display": "GERD", "type": "DISEASE"},
        {"code": "N39.0", "display": "nhiễm khuẩn đường tiết niệu", "type": "DISEASE"},
        {"code": "N39.0", "display": "nhiễm trùng đường tiết niệu", "type": "DISEASE"},
        {"code": "C92.1", "display": "bạch cầu dòng tủy mạn tính", "type": "DISEASE"},
        {"code": "C92.1", "display": "bạch cầu dòng tủy mãn tính", "type": "DISEASE"},
        {"code": "E78.5", "display": "tăng lipid máu", "type": "DISEASE"},
        {"code": "E78.5", "display": "rối loạn lipid máu", "type": "DISEASE"},
        {"code": "M48.0", "display": "hẹp ống sống", "type": "DISEASE"},
        {"code": "L50.9", "display": "mày đay", "type": "DISEASE"},
        {"code": "L50.9", "display": "nổi mề đay", "type": "DISEASE"},
        {"code": "O14.9", "display": "tiền sản giật", "type": "DISEASE"},
        {"code": "F10.2", "display": " nghiện rượu", "type": "DISEASE"},
        {"code": "D64.9", "display": "thiếu máu", "type": "DISEASE"},
        {"code": "D59.9", "display": "tan huyết", "type": "DISEASE"},
        {"code": "D59.9", "display": "thiếu máu tan huyết", "type": "DISEASE"},
        {"code": "N04", "display": "hội chứng thận hư", "type": "DISEASE"},
        {"code": "K76.0", "display": "gan nhiễm mỡ", "type": "DISEASE"},
        {"code": "K80", "display": "sỏi mật", "type": "DISEASE"},
        {"code": "N20.1", "display": "sỏi thận", "type": "DISEASE"},
        {"code": "K35", "display": "viêm ruột thừa", "type": "DISEASE"},
        {"code": "A82", "display": "bệnh dại", "type": "DISEASE"},
        {"code": "B01.9", "display": "thủy đậu", "type": "DISEASE"},
        {"code": "B05", "display": "bệnh sởi", "type": "DISEASE"},
        {"code": "A90", "display": "sốt xuất huyết", "type": "DISEASE"},
        {"code": "A99", "display": "sốt siêu vi", "type": "DISEASE"},
        {"code": "J11", "display": "cảm cúm", "type": "DISEASE"},
        {"code": "F32.9", "display": "trầm cảm", "type": "DISEASE"},
        {"code": "F41.9", "display": "rối loạn lo âu", "type": "DISEASE"},
        {"code": "E85.9", "display": "thoái hóa tinh bột", "type": "DISEASE"},
        {"code": "E85.9", "display": "amyloidosis", "type": "DISEASE"},
        {"code": "I21.9", "display": "nhồi máu cơ tim", "type": "DISEASE"},

        # SYMPTOMS (TRIỆU_CHỨNG) - ICD-10
        {"code": "R25.1", "display": "run tay", "type": "SYMPTOM"},
        {"code": "R25.1", "display": "run tay chân", "type": "SYMPTOM"},
        {"code": "R25.1", "display": "run rẩy toàn thân", "type": "SYMPTOM"},
        {"code": "R25.1", "display": "run chân tay", "type": "SYMPTOM"},
        {"code": "H93.1", "display": "ù tai", "type": "SYMPTOM"},
        {"code": "H53.9", "display": "rối loạn thị lực", "type": "SYMPTOM"},
        {"code": "H53.2", "display": "nhìn song thị", "type": "SYMPTOM"},
        {"code": "R26.8", "display": "mất thăng bằng", "type": "SYMPTOM"},
        {"code": "R26.8", "display": "mất thăng bằng khi đi", "type": "SYMPTOM"},
        {"code": "R00.0", "display": "tim đập nhanh", "type": "SYMPTOM"},
        {"code": "R00.0", "display": "hồi hộp đánh trống ngực", "type": "SYMPTOM"},
        {"code": "R17", "display": "vàng da", "type": "SYMPTOM"},
        {"code": "R17", "display": "vàng mắt", "type": "SYMPTOM"},
        {"code": "R17", "display": "vàng niêm mạc", "type": "SYMPTOM"},
        {"code": "R50.9", "display": "sốt", "type": "SYMPTOM"},
        {"code": "R50.9", "display": "sốt cao", "type": "SYMPTOM"},
        {"code": "R50.9", "display": "sốt nhẹ", "type": "SYMPTOM"},
        {"code": "R50.9", "display": "sốt nóng", "type": "SYMPTOM"},
        {"code": "R68.83", "display": "gai rét", "type": "SYMPTOM"},
        {"code": "R68.83", "display": "rét run", "type": "SYMPTOM"},
        {"code": "R68.83", "display": "ớn lạnh", "type": "SYMPTOM"},
        {"code": "R06.0", "display": "khó thở", "type": "SYMPTOM"},
        {"code": "R06.02", "display": "gắng sức", "type": "SYMPTOM"},
        {"code": "R53.83", "display": "mệt mỏi", "type": "SYMPTOM"},
        {"code": "R53.83", "display": "mệt mỏi nhiều", "type": "SYMPTOM"},
        {"code": "R52", "display": "đau", "type": "SYMPTOM"},
        {"code": "R10.9", "display": "đau bụng", "type": "SYMPTOM"},
        {"code": "R10.9", "display": "đau bụng râm ran", "type": "SYMPTOM"},
        {"code": "R07.4", "display": "đau ngực", "type": "SYMPTOM"},
        {"code": "R07.89", "display": "tức ngực", "type": "SYMPTOM"},
        {"code": "R51", "display": "đau đầu", "type": "SYMPTOM"},
        {"code": "R07.0", "display": "đau họng", "type": "SYMPTOM"},
        {"code": "M25.50", "display": "đau khớp", "type": "SYMPTOM"},
        {"code": "R11.0", "display": "buồn nôn", "type": "SYMPTOM"},
        {"code": "R11", "display": "nôn", "type": "SYMPTOM"},
        {"code": "R11.1", "display": "nôn mửa", "type": "SYMPTOM"},
        {"code": "R19.7", "display": "tiêu chảy", "type": "SYMPTOM"},
        {"code": "R42", "display": "chóng mặt", "type": "SYMPTOM"},
        {"code": "R05", "display": "ho", "type": "SYMPTOM"},
        {"code": "R05", "display": "ho khan", "type": "SYMPTOM"},
        {"code": "R05", "display": "ho đờm", "type": "SYMPTOM"},
        {"code": "R09.82", "display": "sổ mũi", "type": "SYMPTOM"},
        {"code": "R56.9", "display": "co giật", "type": "SYMPTOM"},
        {"code": "R60.9", "display": "phù nề", "type": "SYMPTOM"},
        {"code": "R60.9", "display": "phù", "type": "SYMPTOM"},
        {"code": "R21", "display": "nổi mẩn đỏ", "type": "SYMPTOM"},
        {"code": "R21", "display": "nổi mẩn", "type": "SYMPTOM"},
        {"code": "R63.0", "display": "chán ăn", "type": "SYMPTOM"},
        {"code": "R63.4", "display": "sụt cân", "type": "SYMPTOM"},
        {"code": "G47.0", "display": "mất ngủ", "type": "SYMPTOM"},
        {"code": "R20.2", "display": "tê bì", "type": "SYMPTOM"},
        {"code": "R20.2", "display": "tê tay chân", "type": "SYMPTOM"},
        {"code": "R43.8", "display": "mất vị giác", "type": "SYMPTOM"},
        {"code": "R68.2", "display": "khô miệng", "type": "SYMPTOM"},

        # MEDICINES (THUỐC) - RxNorm
        {"code": "RxNorm:161", "display": "Paracetamol", "type": "MEDICINE"},
        {"code": "RxNorm:161", "display": "Panadol", "type": "MEDICINE"},
        {"code": "RxNorm:161", "display": "acetaminophen", "type": "MEDICINE"},
        {"code": "RxNorm:5640", "display": "Ibuprofen", "type": "MEDICINE"},
        {"code": "RxNorm:7052", "display": "Amoxicillin", "type": "MEDICINE"},
        {"code": "RxNorm:221142", "display": "Augmentin", "type": "MEDICINE"},
        {"code": "RxNorm:6809", "display": "Metformin", "type": "MEDICINE"},
        {"code": "RxNorm:6809", "display": "Glucophage", "type": "MEDICINE"},
        {"code": "RxNorm:17767", "display": "Amlodipine", "type": "MEDICINE"},
        {"code": "RxNorm:5856", "display": "Insulin", "type": "MEDICINE"},
        {"code": "RxNorm:202433", "display": "Decolgen", "type": "MEDICINE"},
        {"code": "RxNorm:9504", "display": "Salbutamol", "type": "MEDICINE"},
        {"code": "RxNorm:9504", "display": "Ventolin", "type": "MEDICINE"},
        {"code": "RxNorm:1191", "display": "Aspirin", "type": "MEDICINE"},
        {"code": "RxNorm:7980", "display": "Penicillin", "type": "MEDICINE"},
        {"code": "RxNorm:2582", "display": "Ciprofloxacin", "type": "MEDICINE"},
        {"code": "RxNorm:7646", "display": "Omeprazole", "type": "MEDICINE"},
        {"code": "RxNorm:7646", "display": "Nexium", "type": "MEDICINE"},
        {"code": "RxNorm:83367", "display": "Atorvastatin", "type": "MEDICINE"},
        {"code": "RxNorm:83367", "display": "Lipitor", "type": "MEDICINE"},
        {"code": "RxNorm:32843", "display": "Loratadine", "type": "MEDICINE"},
        {"code": "RxNorm:232158", "display": "Gliclazide", "type": "MEDICINE"},
        {"code": "RxNorm:3827", "display": "Enalapril", "type": "MEDICINE"},
        {"code": "RxNorm:8640", "display": "Prednisolone", "type": "MEDICINE"},
        {"code": "RxNorm:312271", "display": "Paracetamol 500mg", "type": "MEDICINE"},
        {"code": "RxNorm:282388", "display": "gleevec", "type": "MEDICINE"},
        {"code": "RxNorm:282388", "display": "imatinib", "type": "MEDICINE"},
        {"code": "RxNorm:202433", "display": "tylenol", "type": "MEDICINE"},
        {"code": "RxNorm:656", "display": "allopurinol", "type": "MEDICINE"},
        {"code": "RxNorm:220068", "display": "coumadin", "type": "MEDICINE"},
        {"code": "RxNorm:353062", "display": "suboxone", "type": "MEDICINE"},
        {"code": "RxNorm:3640", "display": "doxycycline", "type": "MEDICINE"},
        {"code": "RxNorm:135834", "display": "bactrim", "type": "MEDICINE"},
        {"code": "RxNorm:8640", "display": "prednisone", "type": "MEDICINE"},
        {"code": "RxNorm:11289", "display": "warfarin", "type": "MEDICINE"},
        {"code": "RxNorm:11246", "display": "vitamin K", "type": "MEDICINE"},
        {"code": "RxNorm:1976", "display": "long não", "type": "MEDICINE"},
        {"code": "RxNorm:7245", "display": "băng phiến", "type": "MEDICINE"},
        {"code": "RxNorm:313360", "display": "đậu tằm", "type": "MEDICINE"},
        {"code": "RxNorm:38413", "display": "Vastarel", "type": "MEDICINE"},
        {"code": "RxNorm:38413", "display": "thuốcVastarel", "type": "MEDICINE"},
        {"code": "RxNorm:38413", "display": "Trimetazidine", "type": "MEDICINE"},
        {"code": "RxNorm:7435", "display": "Nitralmyl", "type": "MEDICINE"},
        {"code": "RxNorm:7435", "display": "Nitroglycerin", "type": "MEDICINE"},
        {"code": "RxNorm:10370", "display": "Tenofovir", "type": "MEDICINE"},
        {"code": "RxNorm:35827", "display": "Entecavir", "type": "MEDICINE"},
        {"code": "RxNorm:32968", "display": "Clopidogrel", "type": "MEDICINE"},
        {"code": "RxNorm:32968", "display": "Plavix", "type": "MEDICINE"},

        # TESTS (TÊN_XÉT_NGHIỆM)
        {"code": "CT", "display": "chụp CT", "type": "TEST"},
        {"code": "CT", "display": "chụp ct", "type": "TEST"},
        {"code": "CT", "display": "chụp cắt lớp vi tính", "type": "TEST"},
        {"code": "MR", "display": "chụp MRI", "type": "TEST"},
        {"code": "MR", "display": "chụp mri", "type": "TEST"},
        {"code": "MR", "display": "chụp cộng hưởng từ", "type": "TEST"},
        {"code": "XR", "display": "chụp X-quang", "type": "TEST"},
        {"code": "XR", "display": "chụp x-quang", "type": "TEST"},
        {"code": "XR", "display": "X-quang", "type": "TEST"},
        {"code": "BL", "display": "xét nghiệm máu", "type": "TEST"},
        {"code": "BL", "display": "xét nghiệm công thức máu", "type": "TEST"},
        {"code": "UA", "display": "xét nghiệm nước tiểu", "type": "TEST"},
        {"code": "US", "display": "siêu âm", "type": "TEST"},
        {"code": "US", "display": "siêu âm bụng", "type": "TEST"},
        {"code": "US", "display": "siêu âm buồng trứng", "type": "TEST"},
        {"code": "ECHO", "display": "siêu âm tim", "type": "TEST"},
        {"code": "ECG", "display": "đo điện tâm đồ", "type": "TEST"},
        {"code": "ECG", "display": "điện tâm đồ", "type": "TEST"},
        {"code": "ECG", "display": "ECG", "type": "TEST"},
        {"code": "END", "display": "nội soi", "type": "TEST"},
        {"code": "END", "display": "nội soi dạ dày", "type": "TEST"},
        {"code": "BIO", "display": "sinh thiết", "type": "TEST"},
        {"code": "BP", "display": "đo huyết áp", "type": "TEST"},
        {"code": "LFT", "display": "xét nghiệm chức năng gan", "type": "TEST"},
        {"code": "CXR", "display": "chụp X-quang phổi", "type": "TEST"},
        {"code": "SA", "display": "xét nghiệm tinh dịch đồ", "type": "TEST"},
        {"code": "SA", "display": "tinh dịch đồ", "type": "TEST"},
        {"code": "HSG", "display": "chụp tử cung vòi trứng", "type": "TEST"},
        {"code": "PAP", "display": "xét nghiệm Pap", "type": "TEST"}
    ]
    from scratch.build_clinical_drug_rxnorm import get_clinical_drug_rxnorm_map
    concepts.extend(get_clinical_drug_rxnorm_map())
    return concepts

if __name__ == "__main__":
    c = get_comprehensive_concepts()
    print(f"Generated {len(c)} concepts!")
